# NUMERICAL PYTHON (01)

In [12]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.shape)
print(a.size)

[[1 2 3 4]
 [5 6 7 8]]
2
8
int64
(2, 4)
8


In [10]:
l=[1,2,3,4]
print(type(l))
arr=np.array(l)
print("array",arr)
print("list",l)

<class 'list'>
array [1 2 3 4]
list [1, 2, 3, 4]


In [19]:
import numpy as np
l=[[[[[[[1,2],[3,4],[5,6],[7,8]]]]]]]
arr1=np.array(l)
print(arr1)
print(arr1.ndim)

[[[[[[[1 2]
      [3 4]
      [5 6]
      [7 8]]]]]]]
7


In [11]:
# CHECKING DATA TYPE OF AN ARRAY
import numpy as np
l=[1,3,5,7,9]
abc=np.array(l)
print(abc)
print(abc.dtype)

[1 3 5 7 9]
int64


In [9]:
# CHECKING DIMENSIONS OF AN ARRAY
import numpy as np
L=[1,2,3,4,5,6,7,8,9]
a3=np.array(l)
print(a3)
print(a3.ndim)

[1 3 5 7 9]
1


In [12]:
# CHECKING SIZE OF AN ARRAY
import numpy as np
l=[1,3,5,7,9]
abc=np.array(l)
print(abc.size)
print(abc)

5
[1 3 5 7 9]


In [2]:
# CONVERTING DATA TYPE INT x TO INT 8
import numpy as np
l=[100,300,500,700,99999]
abc=np.array(l,dtype=np.int8)
print(abc.dtype)
print(abc)


int8
[100  44 -12 -68 -97]


In [28]:
# CREATION OF 2 DIMENSIONAL ARRAY
l=([1,2],[3,4])
a23=np.array(l)
print(l)
print("DIMENSIONS =",a23.ndim)

([1, 2], [3, 4])
DIMENSIONS = 2


In [39]:
# USE OF NP.ZEROS
import numpy as np
A=np.zeros((5),dtype=np.int32)
print(A)

[0 0 0 0 0]


In [13]:
# USE OF NP.ONES
import numpy as np
B=np.ones(([10,2]),dtype=np.int32)
print(B)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [17]:
# USE OF NP.FULL
import numpy as np
C=np.full([7,2],8)
print(C)

[[8 8]
 [8 8]
 [8 8]
 [8 8]
 [8 8]
 [8 8]
 [8 8]]


In [22]:
# USE OF ARANGE 
import numpy as np
A2=np.arange(1,10,2)
print("list of odd no.:",A2)

list of odd no.: [1 3 5 7 9]


In [28]:
# USE OF ARANGE
import numpy as np
A2=np.arange(2,10,2)
print("list of even no.:",A2)

list of even no.: [2 4 6 8]


In [10]:
# USE OF RANDOM
import numpy as np
K=np.random.randint(1,10,3)
print("Random no. b/w 1 to 10:",K)

Random no. b/w 1 to 10: [6 4 6]


In [3]:
# USE OF LINSPACE
import numpy as np
L=np.linspace(2,12,3,dtype=np.int32)
print(L)

[ 2  7 12]


In [13]:
# USE OF ARRANGE TILL 9999
import numpy as np
N=np.arange(999)
print(N)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [16]:
#ARANGING THROUGH PRINT DIRECTLY
import numpy as np
print(np.arange(9999))

[   0    1    2 ... 9996 9997 9998]


# Numerical Python Class Practical Assignment

## Q1 Create an array of 10 elements with values 10 to 1

In [40]:
import numpy as np
A=0
for A in np.arange(10,1):
    V=np.array(L)
print(V)
    


[10  9  8  7  6  5  4  3  2  1]


## Q2 Create an array of 3*3 filled with value 10

In [19]:
import numpy as np
H=np.full([3,3],10)
print(H)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


## Q3 Create an array of 20 elements with random numbers between 50 and 100

In [24]:
import numpy as np
R=np.random.randint(50,100,20)
print("Random no. b/w 50 to 100:",R)

Random no. b/w 50 to 100: [62 53 97 86 99 54 90 79 78 50 84 85 93 93 56 67 66 81 76 83]


## Q4 Create an array of 10 elements with values between 1 to 25 with uniform interval

In [33]:
import numpy as np
L=np.linspace(1,25,10,dtype=np.int32)
print(L)

[ 1  3  6  9 11 14 17 19 22 25]


## Q5 Create a code to store squares of all elements in array

In [61]:
import numpy as np
y=[]
for x in range(1,11):
    y=y+[x**2]
a=np.array(y)
print(y)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


## Q6 Write a code to generate random number between 1 and 100. create array of 5X5

In [1]:
import numpy as np
A=np.random.randint(1,100,(5,5))
print(A)


[[12 22 20 93 81]
 [79 50  8 62  4]
 [35 20 99 19 34]
 [83 14 68 10 29]
 [70 42 81  3 80]]
